apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-service-deployment
  namespace: natter-api
spec:
  selector:
    matchLabels:
      app: token-service
  replicas: 1
  template:
    metadata:
      labels:
        app: token-service
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: token-service
          image: apisecurityinaction/token-service:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          ports:
            - containerPort: 4567